version: '3.8'

services:
  crtraslochi_frontend:
    container_name: crtraslochi_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5182:3000'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - crtraslochi-network

networks:
  crtraslochi-network:
    driver: bridge
